# Generated by Django 4.1.7 on 2023-03-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(1, '特级'), (2, '一级'), (3, '二级'), (4, '三级')], default=2, verbose_name='等级')),
                ('status', models.SmallIntegerField(choices=[(1, '已售出'), (2, '已预订'), (3, '待销售')], default=3, verbose_name='状态')),
                ('zone', models.CharField(blank=True, max_length=64, null=True, verbose_name='地区')),
            ],
        ),
    ]
