# Generated by Django 4.1.7 on 2023-03-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_department_usersinfo_delete_departlist_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersInfo',
            new_name='UserInfo',
        ),
    ]
