# Generated by Django 4.1.7 on 2023-03-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_prettynum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='mobile',
            field=models.CharField(max_length=64, verbose_name='手机号'),
        ),
    ]
