# Generated by Django 4.1.7 on 2023-03-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_usersinfo_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
