# Generated by Django 4.1.7 on 2023-03-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
