# Generated by Django 4.1.7 on 2023-03-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='role',
        ),
    ]
