# Generated by Django 4.1.7 on 2023-03-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='User_Info',
        ),
    ]
