# Generated by Django 4.1.7 on 2023-03-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_userinfo_user_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Info',
            new_name='UserInfo',
        ),
    ]
