# Generated by Django 4.1.7 on 2023-03-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_user_info_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
